# Generated by Django 4.2.30 on 2026-06-07 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 7, 13, 3, 38, 26381)),
        ),
    ]
